version: "3.2"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /root/son/elk/esdata:/usr/share/elasticsearch/data
  logstash:
    image: docker.elastic.co/logstash/logstash:7.3.1
    ports:
      - 5044:5044
    volumes:
      - /root/son/elk/testpattern:/usr/share/logstash/testpattern
      - /root/son/elk/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - es
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    user: root
    network_mode: "host"
    volumes:
      - /root/son/elk/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
      - /opt/tomcat/apache-tomcat-7.0.91/logs:/root/tomcat_logs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - es
      - logstash
